import { supabase } from "../lib/supabase";
import { createNotification } from "./notificationService";
import { logActivity } from "./activityService";
import type { AccountRiskSummary, AppealStatus, EnforcementAction, EnforcementActionType, EnforcementAppeal } from "../types/enforcement";

async function currentUser(){const {data,error}=await supabase.auth.getUser();if(error)throw error;if(!data.user)throw new Error("Session expired.");return data.user;}
export async function getRiskSummaries(ids?:string[]):Promise<AccountRiskSummary[]>{const {data,error}=await supabase.rpc("get_account_risk_summary",{requested_user_ids:ids?.length?ids:null});if(error)throw error;return (data??[]).map((r:any)=>({...r,warning_points:Number(r.warning_points??0),warning_count:Number(r.warning_count??0),suspension_count:Number(r.suspension_count??0),valid_case_count:Number(r.valid_case_count??0)}));}
export async function getAdminRiskProfiles(){const {data:profiles,error}=await supabase.from("profiles").select("id,first_name,last_name,email,role,status").in("role",["customer","worker"]);if(error)throw error;const risks=await getRiskSummaries((profiles??[]).map((p:any)=>p.id));const map=new Map(risks.map(r=>[r.user_id,r]));return (profiles??[]).map((p:any)=>({...p,risk:map.get(p.id)??null}));}
export async function getUserEnforcements(userId?:string):Promise<EnforcementAction[]>{const uid=userId??(await currentUser()).id;const {data,error}=await supabase.from("enforcement_actions").select("*").eq("user_id",uid).order("created_at",{ascending:false});if(error)throw error;return (data??[]) as EnforcementAction[];}
export async function issueEnforcement(input:{userId:string;reportId?:string|null;actionType:EnforcementActionType;points:number;reason:string;durationDays?:number|null}){const admin=await currentUser();const reason=input.reason.trim();if(reason.length<10)throw new Error("Reason must contain at least 10 characters.");const ends=input.actionType==="suspension"&&input.durationDays?new Date(Date.now()+input.durationDays*86400000).toISOString():null;const {data,error}=await supabase.from("enforcement_actions").insert({user_id:input.userId,report_id:input.reportId??null,action_type:input.actionType,points:input.points,reason,ends_at:ends,issued_by:admin.id}).select().single();if(error)throw error;if(input.actionType==="suspension"){const p=await supabase.from("profiles").update({status:"Disabled"}).eq("id",input.userId);if(p.error)throw p.error;}await Promise.allSettled([createNotification(input.userId,null,input.actionType==="warning"?"Official Account Warning":"Account Enforcement Action",reason),logActivity(admin.id,"ENFORCEMENT","Trust & Safety",`${input.actionType} issued to ${input.userId}.`)]);return data as EnforcementAction;}
export async function reverseEnforcement(action:EnforcementAction,reason:string){const admin=await currentUser();const {error}=await supabase.from("enforcement_actions").update({status:"reversed",reversed_by:admin.id,reversal_reason:reason}).eq("id",action.id);if(error)throw error;if(action.action_type==="suspension"){await supabase.from("profiles").update({status:"Approved"}).eq("id",action.user_id);}await createNotification(action.user_id,null,"Penalty Reversed",reason);}
export async function getMyAppeals():Promise<EnforcementAppeal[]>{const user=await currentUser();const {data,error}=await supabase.from("enforcement_appeals").select("*, enforcement:enforcement_actions(*)").eq("appellant_id",user.id).order("created_at",{ascending:false});if(error)throw error;return (data??[]) as EnforcementAppeal[];}
export async function getMyAppealableActions(){const user=await currentUser();const [actions,appeals]=await Promise.all([getUserEnforcements(user.id),getMyAppeals()]);const used=new Set(appeals.map(a=>a.enforcement_id));return actions.filter(a=>a.status==="active"&&!used.has(a.id));}
export async function submitAppeal(input:{enforcementId:string;reason:string;requestedOutcome?:string}){const user=await currentUser();const {data,error}=await supabase.from("enforcement_appeals").insert({enforcement_id:input.enforcementId,appellant_id:user.id,reason:input.reason.trim(),requested_outcome:input.requestedOutcome?.trim()||null}).select().single();if(error)throw error;return data as EnforcementAppeal;}
export async function getAdminAppeals():Promise<EnforcementAppeal[]>{const {data,error}=await supabase.from("enforcement_appeals").select("*, enforcement:enforcement_actions(*), appellant:profiles!appellant_id(id,first_name,last_name,email,role)").order("created_at",{ascending:false});if(error)throw error;return (data??[]) as EnforcementAppeal[];}
export async function reviewAppeal(appeal:EnforcementAppeal,status:AppealStatus,response:string){const admin=await currentUser();const text=response.trim();if(text.length<10)throw new Error("Admin response must contain at least 10 characters.");const {error}=await supabase.from("enforcement_appeals").update({status,admin_response:text,reviewed_by:admin.id,reviewed_at:new Date().toISOString()}).eq("id",appeal.id);if(error)throw error;if((status==="approved"||status==="partially_approved")&&appeal.enforcement){await reverseEnforcement(appeal.enforcement,text);}await createNotification(appeal.appellant_id,null,"Appeal Decision",text);}
