import { useCallback, useEffect, useMemo, useState } from "react";
import { Eye, RefreshCw, Search, X } from "lucide-react";
import { toast } from "sonner";
import AdminLayout from "../../../layouts/AdminLayout";
import { supabase } from "../../../lib/supabase";
type Project={id:number;customer_id:string;title:string;category:string;location:string;start_date:string;workers_needed:number;pricing_type:string;rate:number;status:string;created_at:string;customer_name?:string};
type Profile={id:string;full_name?:string|null;first_name?:string|null;last_name?:string|null};
type TeamMember={id:string|number;worker_id:string;role?:string;status?:string;agreed_rate?:number};
type Application={id:string|number;worker_id:string};
type Attendance={id:string|number;worker_id:string;work_date?:string;attendance_status?:string;minutes_worked?:number;accomplishment?:string|null};
type Payment={id:string|number;worker_id:string;payment_kind?:string;amount?:number;status?:string};
type Task={id:string|number;assigned_worker_id?:string|null;title?:string;priority?:string;status?:string};
type Detail={team:TeamMember[];applications:Application[];attendance:Attendance[];payments:Payment[];tasks:Task[];names:Map<string,string>};
const money=(n?:number)=>new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"}).format(n||0);
const name=(p:Profile)=>p.full_name?.trim()||`${p.first_name||""} ${p.last_name||""}`.trim()||"User";
export default function AdminProjects(){const [rows,setRows]=useState<Project[]>([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[q,setQ]=useState(""),[filter,setFilter]=useState("All"),[selected,setSelected]=useState<Project|null>(null),[detail,setDetail]=useState<Detail|null>(null),[detailLoading,setDetailLoading]=useState(false);
const load=useCallback(async(bg=false)=>{if(bg){setRefreshing(true)}else{setLoading(true)}try{const {data,error}=await supabase.from("projects").select("*").order("created_at",{ascending:false});if(error)throw error;const r=(data||[]) as Project[];const ids=[...new Set(r.map(x=>x.customer_id))];let nm=new Map<string,string>();if(ids.length){const {data:p}=await supabase.from("profiles").select("id,full_name,first_name,last_name").in("id",ids);nm=new Map(((p||[]) as Profile[]).map(x=>[x.id,name(x)]));}setRows(r.map(x=>({...x,customer_name:nm.get(x.customer_id)||"Customer"})));}catch(e){toast.error(e instanceof Error?e.message:"Unable to load projects.")}finally{setLoading(false);setRefreshing(false)}},[]);
useEffect(()=>{void Promise.resolve().then(()=>load());const c=supabase.channel("admin-projects-monitor").on("postgres_changes",{event:"*",schema:"public",table:"projects"},()=>void load(true)).subscribe();return()=>{void supabase.removeChannel(c)}},[load]);
const open=async(p:Project)=>{setSelected(p);setDetail(null);setDetailLoading(true);try{const queries=[
  ["team",supabase.from("project_team_members").select("*").eq("project_id",p.id)],
  ["applications",supabase.from("project_applications").select("*").eq("project_id",p.id)],
  ["attendance",supabase.from("project_attendance").select("*").eq("project_id",p.id).order("work_date",{ascending:false})],
  ["payments",supabase.from("project_worker_payments").select("*").eq("project_id",p.id)],
  ["tasks",supabase.from("project_tasks").select("*").eq("project_id",p.id)]
] as const;
const settled=await Promise.all(queries.map(async([key,query])=>{const result=await query;return {key,data:result.data||[],error:result.error}}));
const failed=settled.filter(x=>x.error);if(failed.length){console.error("Admin project workspace partial load errors",failed.map(x=>({section:x.key,error:x.error})));toast.warning(`Some project sections could not be loaded: ${failed.map(x=>x.key).join(", ")}. Apply the Admin Project Workspace SQL migration if this persists.`);}
const section=(key:string)=>settled.find(x=>x.key===key)?.data||[];
const team=section("team") as TeamMember[],apps=section("applications") as Application[],attendance=section("attendance") as Attendance[],payments=section("payments") as Payment[],tasks=section("tasks") as Task[];
const ids=[...new Set([...team.map(x=>x.worker_id),...apps.map(x=>x.worker_id),...attendance.map(x=>x.worker_id),...payments.map(x=>x.worker_id),...tasks.map(x=>x.assigned_worker_id)].filter(Boolean))];let nm=new Map<string,string>();if(ids.length){const {data:pr,error:profileError}=await supabase.from("profiles").select("id,full_name,first_name,last_name").in("id",ids);if(profileError)console.error("Unable to load project worker names",profileError);else nm=new Map(((pr||[]) as Profile[]).map(x=>[x.id,name(x)]));}setDetail({team,applications:apps,attendance,payments,tasks,names:nm});}catch(e){console.error("Unable to load admin project workspace",e);setDetail({team:[],applications:[],attendance:[],payments:[],tasks:[],names:new Map()});toast.error(e instanceof Error?e.message:"Unable to load project workspace.")}finally{setDetailLoading(false)}};
const shown=useMemo(()=>rows.filter(x=>(filter==="All"||x.status===filter)&&`${x.title} ${x.category} ${x.location} ${x.customer_name}`.toLowerCase().includes(q.toLowerCase())),[rows,q,filter]);const statuses=[...new Set(rows.map(x=>x.status))];
return <AdminLayout><div className="space-y-5 p-4 sm:p-6 lg:p-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-black">Projects</h1><p className="text-sm text-slate-500">Admin monitoring for customer-posted and booking-linked projects.</p></div><button onClick={()=>void load(true)} className="flex items-center gap-2 rounded-xl border bg-white px-4 py-2 font-bold"><RefreshCw size={16} className={refreshing?"animate-spin":""}/>Refresh</button></div><div className="grid gap-3 sm:grid-cols-4">{[["All",rows.length],["Open",rows.filter(x=>x.status==="Open").length],["Active",rows.filter(x=>x.status==="In Progress"||x.status==="Completion Review").length],["Completed",rows.filter(x=>x.status==="Completed").length]].map(x=><div className="rounded-2xl border bg-white p-4" key={String(x[0])}><p className="text-xs font-bold uppercase text-slate-500">{x[0]}</p><p className="text-2xl font-black">{x[1]}</p></div>)}</div><div className="flex gap-3 rounded-2xl border bg-white p-4"><div className="relative flex-1"><Search size={17} className="absolute left-3 top-3 text-slate-400"/><input className="w-full rounded-xl border px-9 py-2.5" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search projects..."/></div><select className="rounded-xl border px-3" value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></div><div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[850px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Project</th><th>Customer</th><th>Workers</th><th>Pricing</th><th>Start</th><th>Status</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan={7} className="p-10 text-center">Loading...</td></tr>:shown.map(p=><tr className="border-t" key={p.id}><td className="p-4"><b>{p.title}</b><div className="text-xs text-slate-500">{p.category} · {p.location}</div></td><td>{p.customer_name}</td><td>{p.workers_needed}</td><td className="capitalize">{p.pricing_type} · {money(p.rate)}</td><td>{p.start_date}</td><td><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{p.status}</span></td><td><button onClick={()=>void open(p)} className="flex items-center gap-1 rounded-lg border px-3 py-2 font-bold text-blue-700"><Eye size={15}/>View</button></td></tr>)}</tbody></table>{!loading&&!shown.length&&<div className="p-10 text-center text-slate-500">No projects found.</div>}</div>
{selected&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/55 p-3"><div className="max-h-[92vh] w-full max-w-5xl overflow-y-auto rounded-3xl bg-white"><header className="sticky top-0 flex items-center justify-between border-b bg-white p-5"><div><h2 className="text-xl font-black">{selected.title}</h2><p className="text-sm text-slate-500">Admin Project Workspace · {selected.customer_name}</p></div><button onClick={()=>setSelected(null)} className="rounded-xl border p-2"><X/></button></header><div className="space-y-5 p-5">{detailLoading?<p className="p-8 text-center">Loading workspace...</p>:detail&&<><div className="grid gap-3 sm:grid-cols-5">{[["Status",selected.status],["Team",`${detail.team.filter(x=>x.status==="Active").length}/${selected.workers_needed}`],["Applicants",detail.applications.length],["Tasks",detail.tasks.length],["Payments",detail.payments.length]].map(x=><div className="rounded-xl bg-slate-50 p-3" key={String(x[0])}><b className="text-xs uppercase text-slate-500">{x[0]}</b><p className="font-bold">{x[1]}</p></div>)}</div><section><h3 className="mb-2 font-black">Team Members</h3><div className="grid gap-2 sm:grid-cols-2">{detail.team.map(m=><div className="rounded-xl border p-3" key={m.id}><b>{detail.names.get(m.worker_id)||"Worker"}</b><p className="text-sm text-slate-500">{m.role} · {m.status} · {money(m.agreed_rate)}</p></div>)}{!detail.team.length&&<p className="text-sm text-slate-500">No team members yet.</p>}</div></section><section><h3 className="mb-2 font-black">Tasks</h3>{detail.tasks.map(t=><div className="mb-2 rounded-xl border p-3" key={t.id}><b>{t.title}</b><p className="text-sm text-slate-500">{detail.names.get(t.assigned_worker_id||"")||"Worker"} · {t.priority} · {t.status}</p></div>)}{!detail.tasks.length&&<p className="text-sm text-slate-500">No tasks yet.</p>}</section><section><h3 className="mb-2 font-black">Attendance / Logbook</h3><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead><tr className="border-b text-left"><th className="py-2">Date</th><th>Worker</th><th>Status</th><th>Minutes</th><th>Accomplishment</th></tr></thead><tbody>{detail.attendance.map(a=><tr className="border-b" key={a.id}><td className="py-2">{a.work_date}</td><td>{detail.names.get(a.worker_id)||"Worker"}</td><td>{a.attendance_status}</td><td>{a.minutes_worked||0}</td><td>{a.accomplishment||"—"}</td></tr>)}</tbody></table></div>{!detail.attendance.length&&<p className="text-sm text-slate-500">No attendance records.</p>}</section><section><h3 className="mb-2 font-black">Project Payments</h3>{detail.payments.map(p=><div className="mb-2 flex justify-between rounded-xl border p-3" key={p.id}><span>{detail.names.get(p.worker_id)||"Worker"} · {p.payment_kind}</span><b>{money(p.amount)} · {p.status}</b></div>)}{!detail.payments.length&&<p className="text-sm text-slate-500">No payment records.</p>}</section></>}</div></div></div>}</div></AdminLayout>}
