import { AlertTriangle, ArrowLeft, Ban, CheckCircle2, ExternalLink, FileText, LoaderCircle, MessageSquareWarning, Save, ShieldAlert, UserRound, XCircle } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { toast } from "sonner";
import AdminLayout from "../../../layouts/AdminLayout";
import { getAdminCaseDetails, getCasePersonName, issueCaseWarning, suspendReportedUser, updateAdminCase, type AdminCaseDetails } from "../../../services/adminCaseReportService";
import type { ReportPriority, ReportStatus } from "../../../types/report";

const format=(v:string|null|undefined)=>v?new Intl.DateTimeFormat("en-PH",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";
export default function CaseReview(){
 const {reportId=""}=useParams(); const navigate=useNavigate(); const [data,setData]=useState<AdminCaseDetails|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
 const [status,setStatus]=useState<ReportStatus>("submitted"); const [priority,setPriority]=useState<ReportPriority>("medium"); const [notes,setNotes]=useState(""); const [resolution,setResolution]=useState("");
 const load=useCallback(async()=>{try{setLoading(true);const value=await getAdminCaseDetails(reportId);setData(value);setStatus(value.report.status);setPriority(value.report.priority);setNotes(value.report.admin_notes??"");setResolution(value.report.resolution??"");}catch(e){toast.error(e instanceof Error?e.message:"Unable to load case.");}finally{setLoading(false)}},[reportId]);
 useEffect(()=>{void load()},[load]);
 const save=async(nextStatus:ReportStatus=status)=>{if(!data)return;try{setSaving(true);await updateAdminCase({reportId:data.report.id,status:nextStatus,priority,adminNotes:notes,resolution});setStatus(nextStatus);toast.success("Case updated.");await load();}catch(e){toast.error(e instanceof Error?e.message:"Unable to update case.");}finally{setSaving(false)}};
 const warning=async()=>{if(!data)return;const message=window.prompt("Enter the warning message for the reported user:");if(!message)return;try{await issueCaseWarning(data.report.id,data.report.reported_user_id,data.report.booking_id,message);toast.success("Warning sent.");await load();}catch(e){toast.error(e instanceof Error?e.message:"Unable to issue warning.")}};
 const suspend=async()=>{if(!data)return;const reason=window.prompt("Enter the suspension reason. This disables the reported account:");if(!reason)return;if(!window.confirm("Suspend this user's account?"))return;try{await suspendReportedUser(data.report.id,data.report.reported_user_id,reason);toast.success("Account suspended.");await load();}catch(e){toast.error(e instanceof Error?e.message:"Unable to suspend account.")}};
 if(loading)return <AdminLayout><div className="flex min-h-[60vh] items-center justify-center"><LoaderCircle className="animate-spin text-blue-600" size={40}/></div></AdminLayout>;
 if(!data)return <AdminLayout><div className="rounded-2xl border bg-white p-10 text-center">Case not found.</div></AdminLayout>;
 const r=data.report;
 return <AdminLayout><div className="space-y-6">
  <button onClick={()=>navigate("/admin/cases")} className="inline-flex items-center gap-2 font-bold text-slate-600"><ArrowLeft size={18}/>Back to cases</button>
  <div className="rounded-3xl bg-gradient-to-r from-slate-900 via-blue-950 to-indigo-900 p-7 text-white shadow-xl"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-blue-300">{r.case_type} · Booking #{r.booking_id}</p><h1 className="mt-2 text-3xl font-black">{r.subject}</h1><p className="mt-2 text-slate-300">Case #{r.id}</p></div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-white/10 px-4 py-2 font-bold capitalize">{r.priority} priority</span><span className="rounded-full bg-white/10 px-4 py-2 font-bold capitalize">{r.status.replaceAll("_"," ")}</span></div></div></div>
  <div className="grid gap-6 xl:grid-cols-[1.3fr_.7fr]">
   <div className="space-y-6">
    <section className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="flex items-center gap-2 text-xl font-black"><ShieldAlert className="text-blue-600"/>Case statement</h2><div className="mt-5 rounded-2xl bg-slate-50 p-5"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Category</p><p className="mt-1 font-bold text-slate-900">{r.category}</p><p className="mt-5 whitespace-pre-wrap leading-7 text-slate-700">{r.description}</p>{r.requested_resolution&&<><p className="mt-5 text-xs font-bold uppercase tracking-wide text-slate-500">Requested resolution</p><p className="mt-1 text-slate-700">{r.requested_resolution}</p></>}</div></section>
    <section className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="flex items-center gap-2 text-xl font-black"><UserRound className="text-blue-600"/>Participants</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{[["Reporter",r.reporter],["Reported User",r.reported_user]].map(([label,p]:any)=><div key={label} className="rounded-2xl border p-5"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-2 text-lg font-black">{getCasePersonName(p)}</p><p className="mt-1 text-sm text-slate-500">{p?.email??"No email"}</p><p className="mt-3 text-sm capitalize">Role: {p?.role??"—"} · Account: {p?.status??"—"}</p></div>)}</div></section>
    <section className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="flex items-center gap-2 text-xl font-black"><FileText className="text-blue-600"/>Evidence ({data.evidence.length})</h2>{data.evidence.length===0?<p className="mt-5 rounded-2xl bg-slate-50 p-6 text-slate-500">No evidence was uploaded.</p>:<div className="mt-5 grid gap-4 sm:grid-cols-2">{data.evidence.map(e=><a key={e.id} href={e.signed_url??"#"} target="_blank" rel="noreferrer" className="group rounded-2xl border p-4 hover:border-blue-400"><div className="flex items-center justify-between"><div className="min-w-0"><p className="truncate font-bold">{e.file_name}</p><p className="mt-1 text-xs text-slate-500">{e.mime_type} · {(e.file_size/1024).toFixed(1)} KB</p></div><ExternalLink size={18} className="text-blue-600"/></div></a>)}</div>}</section>
    <section className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Case timeline</h2><div className="mt-5 space-y-4">{data.logs.map(log=><div key={log.id} className="relative border-l-2 border-blue-200 pl-5"><span className="absolute -left-[7px] top-1 h-3 w-3 rounded-full bg-blue-600"/><p className="font-bold capitalize">{log.action.replaceAll("_"," ")}</p><p className="mt-1 text-sm text-slate-600">{log.note??"Case activity recorded."}</p><p className="mt-1 text-xs text-slate-400">{format(log.created_at)}</p></div>)}</div></section>
   </div>
   <div className="space-y-6">
    <section className="sticky top-6 rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Investigation controls</h2><label className="mt-5 block text-sm font-bold">Status<select value={status} onChange={e=>setStatus(e.target.value as ReportStatus)} className="mt-2 w-full rounded-xl border px-4 py-3">{["submitted","under_review","needs_more_information","escalated","resolved","rejected","closed"].map(v=><option key={v} value={v}>{v.replaceAll("_"," ")}</option>)}</select></label><label className="mt-4 block text-sm font-bold">Priority<select value={priority} onChange={e=>setPriority(e.target.value as ReportPriority)} className="mt-2 w-full rounded-xl border px-4 py-3">{["low","medium","high","urgent"].map(v=><option key={v} value={v}>{v}</option>)}</select></label><label className="mt-4 block text-sm font-bold">Private admin notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={5} className="mt-2 w-full rounded-xl border p-3" placeholder="Internal investigation notes..."/></label><label className="mt-4 block text-sm font-bold">Public resolution<textarea value={resolution} onChange={e=>setResolution(e.target.value)} rows={4} className="mt-2 w-full rounded-xl border p-3" placeholder="Decision visible to the reporter..."/></label><button disabled={saving} onClick={()=>void save()} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-3 font-bold text-white disabled:opacity-60">{saving?<LoaderCircle className="animate-spin" size={18}/>:<Save size={18}/>}Save Review</button><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>void save("resolved")} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-600 px-3 py-3 text-sm font-bold text-white"><CheckCircle2 size={17}/>Resolve</button><button onClick={()=>void save("rejected")} className="inline-flex items-center justify-center gap-2 rounded-xl bg-rose-600 px-3 py-3 text-sm font-bold text-white"><XCircle size={17}/>Reject</button></div><div className="my-5 border-t"/><button onClick={()=>void warning()} className="inline-flex w-full items-center justify-center gap-2 rounded-xl border border-amber-300 bg-amber-50 px-4 py-3 font-bold text-amber-800"><MessageSquareWarning size={18}/>Warn Reported User</button><button onClick={()=>void suspend()} className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-xl border border-rose-300 bg-rose-50 px-4 py-3 font-bold text-rose-800"><Ban size={18}/>Suspend Reported User</button><p className="mt-4 text-xs leading-5 text-slate-500"><AlertTriangle size={14} className="mr-1 inline"/>Account actions are recorded in the audit trail. Review evidence before applying penalties.</p></section>
    <section className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-black">Related booking</h2><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between gap-3"><dt className="text-slate-500">Booking</dt><dd className="font-bold">#{data.booking?.id??r.booking_id}</dd></div><div className="flex justify-between gap-3"><dt className="text-slate-500">Service</dt><dd className="text-right font-bold">{data.service_name??"—"}</dd></div><div className="flex justify-between gap-3"><dt className="text-slate-500">Status</dt><dd className="font-bold">{data.booking?.status??"—"}</dd></div><div className="flex justify-between gap-3"><dt className="text-slate-500">Schedule</dt><dd className="text-right font-bold">{data.booking?.booking_date??"—"} {data.booking?.booking_time??""}</dd></div><div className="flex justify-between gap-3"><dt className="text-slate-500">Submitted</dt><dd className="text-right font-bold">{format(r.created_at)}</dd></div></dl></section>
   </div>
  </div>
 </div></AdminLayout>
}
