import { AlertTriangle, CheckCircle2, Clock3, Eye, FileWarning, RefreshCw, Search, ShieldAlert } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { toast } from "sonner";
import AdminLayout from "../../../layouts/AdminLayout";
import { getAdminCases, getAdminCaseSummary, getCasePersonName, subscribeToAdminCases, type AdminCaseListItem } from "../../../services/adminCaseReportService";

const statusLabels: Record<string,string> = { submitted:"Submitted", under_review:"Under Review", needs_more_information:"Needs More Information", resolved:"Resolved", rejected:"Rejected", escalated:"Escalated", withdrawn:"Withdrawn", closed:"Closed" };
const badge=(status:string)=> status==="resolved"?"bg-emerald-100 text-emerald-700":status==="rejected"?"bg-rose-100 text-rose-700":status==="under_review"?"bg-blue-100 text-blue-700":"bg-amber-100 text-amber-800";
const formatDate=(v:string)=>new Intl.DateTimeFormat("en-PH",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));

export default function ReportsComplaints(){
 const navigate=useNavigate();
 const [items,setItems]=useState<AdminCaseListItem[]>([]); const [summary,setSummary]=useState<Record<string,number>>({});
 const [loading,setLoading]=useState(true); const [search,setSearch]=useState(""); const [status,setStatus]=useState(""); const [priority,setPriority]=useState(""); const [caseType,setCaseType]=useState("");
 const load=useCallback(async()=>{try{setLoading(true);const [rows,stats]=await Promise.all([getAdminCases({search,status,priority,caseType}),getAdminCaseSummary()]);setItems(rows);setSummary(stats);}catch(e){toast.error(e instanceof Error?e.message:"Unable to load cases.");}finally{setLoading(false)}},[search,status,priority,caseType]);
 useEffect(()=>{void load();return subscribeToAdminCases(()=>void load())},[load]);
 const cards=useMemo(()=>[
  ["Total Cases",summary.total??0,ShieldAlert,"text-slate-700 bg-slate-100"],
  ["Submitted",summary.submitted??0,Clock3,"text-amber-700 bg-amber-100"],
  ["Under Review",summary.under_review??0,FileWarning,"text-blue-700 bg-blue-100"],
  ["High Priority",summary.high_priority??0,AlertTriangle,"text-rose-700 bg-rose-100"],
  ["Resolved",summary.resolved??0,CheckCircle2,"text-emerald-700 bg-emerald-100"],
 ] as const,[summary]);
 return <AdminLayout><div className="space-y-7">
  <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-blue-600">Case Management</p><h1 className="mt-1 text-3xl font-black text-slate-900">Reports & Complaints</h1><p className="mt-2 text-slate-500">Review evidence, investigate disputes, and record fair resolutions.</p></div><button onClick={()=>void load()} className="inline-flex items-center justify-center gap-2 rounded-xl border bg-white px-4 py-3 font-bold text-slate-700"><RefreshCw size={18}/>Refresh</button></div>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([label,value,Icon,cls])=><div key={label} className="rounded-2xl border bg-white p-5 shadow-sm"><div className={`flex h-11 w-11 items-center justify-center rounded-xl ${cls}`}><Icon size={21}/></div><p className="mt-4 text-3xl font-black text-slate-900">{value}</p><p className="mt-1 text-sm font-semibold text-slate-500">{label}</p></div>)}</div>
  <div className="rounded-3xl border bg-white p-5 shadow-sm"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><label className="relative xl:col-span-2"><Search className="absolute left-4 top-3.5 text-slate-400" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search case, person, category or booking..." className="w-full rounded-xl border py-3 pl-11 pr-4 outline-none focus:border-blue-500"/></label><select value={caseType} onChange={e=>setCaseType(e.target.value)} className="rounded-xl border px-4 py-3"><option value="">All types</option><option value="report">Reports</option><option value="complaint">Complaints</option></select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border px-4 py-3"><option value="">All statuses</option>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)} className="rounded-xl border px-4 py-3"><option value="">All priorities</option><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="urgent">Urgent</option></select></div></div>
  <div className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{["Case","Reporter","Reported User","Category","Priority","Status","Submitted",""].map(h=><th key={h} className="px-5 py-4">{h}</th>)}</tr></thead><tbody className="divide-y">{loading?<tr><td colSpan={8} className="px-5 py-16 text-center text-slate-500">Loading cases...</td></tr>:items.length===0?<tr><td colSpan={8} className="px-5 py-16 text-center text-slate-500">No cases matched the filters.</td></tr>:items.map(item=><tr key={item.id} className="hover:bg-slate-50"><td className="px-5 py-4"><p className="font-bold text-slate-900">#{item.id.slice(0,8)}</p><p className="mt-1 text-xs capitalize text-slate-500">{item.case_type} · Booking #{item.booking_id}</p></td><td className="px-5 py-4 font-semibold">{getCasePersonName(item.reporter)}</td><td className="px-5 py-4 font-semibold">{getCasePersonName(item.reported_user)}</td><td className="max-w-48 px-5 py-4"><p className="truncate font-medium">{item.category}</p><p className="truncate text-xs text-slate-500">{item.subject}</p></td><td className="px-5 py-4 capitalize font-bold">{item.priority}</td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${badge(item.status)}`}>{statusLabels[item.status]??item.status}</span></td><td className="whitespace-nowrap px-5 py-4 text-slate-500">{formatDate(item.created_at)}</td><td className="px-5 py-4"><button onClick={()=>navigate(`/admin/cases/${item.id}`)} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-3 py-2 font-bold text-white"><Eye size={16}/>Review</button></td></tr>)}</tbody></table></div></div>
 </div></AdminLayout>
}
