import { useCallback, useEffect, useState } from "react";
import { BookOpen, Play, Square, Users } from "lucide-react";
import { toast } from "sonner";
import { ensureBookingProject, getAttendance, getTeam, timeIn, timeOut, type Attendance, type ProjectPost, type TeamMember } from "../../services/projectMarketplaceService";

type Props = { bookingId:number; role:"worker"|"customer"; pricingType?:string|null; price?:number|string|null; onPayAdvance?:(amount:number)=>void };
export default function ProjectWorkflowPanel({bookingId,role}:Props){
 const [project,setProject]=useState<ProjectPost|null>(null),[team,setTeam]=useState<TeamMember[]>([]),[attendance,setAttendance]=useState<Attendance[]>([]),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const linked=await ensureBookingProject(bookingId);const [members,logs]=await Promise.all([getTeam(linked.id),getAttendance(linked.id)]);setProject(linked);setTeam(members);setAttendance(logs);}catch(e){toast.error(e instanceof Error?e.message:"Unable to load project workspace.");}},[bookingId]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
 const run=async(fn:()=>Promise<void>,message:string)=>{setBusy(true);try{await fn();toast.success(message);await load();}catch(e){toast.error(e instanceof Error?e.message:"Action failed.");}finally{setBusy(false);}};
 if(!project)return <section className="mt-5 rounded-2xl border p-4 text-sm text-slate-500">Loading unified Project workspace…</section>;
 const today=new Date().toISOString().slice(0,10), myToday=attendance.find(a=>a.work_date===today&&!a.time_out);
 return <section className="mt-5 rounded-2xl border border-blue-200 bg-blue-50/60 p-4 dark:border-blue-900 dark:bg-blue-950/20"><div className="flex flex-wrap items-start justify-between gap-3"><div><h4 className="font-black"><BookOpen className="mr-2 inline h-4 w-4"/>Project Workspace & Logbook</h4><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">This booked Project/Multi-day service uses the same team, attendance, daily/hourly payment and completion workspace as posted Projects.</p></div><div className="rounded-xl bg-white px-3 py-2 text-sm font-bold dark:bg-slate-900"><Users className="mr-1 inline h-4 w-4"/>{team.length}/{project.workers_needed} Team · {project.status}</div></div>{role==="worker"&&project.status==="In Progress"&&<div className="mt-4 flex gap-2">{!myToday?<button disabled={busy} onClick={()=>void run(()=>timeIn(project),"Time in recorded.")} className="rounded-xl bg-emerald-600 px-4 py-2 font-bold text-white"><Play className="mr-2 inline h-4 w-4"/>Time In / Start Work</button>:<button disabled={busy} onClick={()=>{const note=prompt("What did you accomplish today?")||"";if(note.trim())void run(()=>timeOut(project,note),"End Work for Today recorded.");}} className="rounded-xl bg-slate-800 px-4 py-2 font-bold text-white"><Square className="mr-2 inline h-4 w-4"/>End Work for Today</button>}</div>}<div className="mt-4 overflow-x-auto rounded-xl bg-white dark:bg-slate-900"><table className="w-full min-w-[650px] text-sm"><thead><tr className="text-left text-slate-500"><th className="p-3">Date</th><th>Worker</th><th>Attendance</th><th>Time In</th><th>Time Out</th><th>Accomplishment</th></tr></thead><tbody>{attendance.slice(0,8).map(a=><tr key={a.id} className="border-t"><td className="p-3">{a.work_date}</td><td>{a.worker_name}</td><td className="font-bold">{a.attendance_status}</td><td>{a.time_in?new Date(a.time_in).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):"—"}</td><td>{a.time_out?new Date(a.time_out).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):"—"}</td><td>{a.accomplishment||"—"}</td></tr>)}</tbody></table>{attendance.length===0&&<p className="p-4 text-center text-sm text-slate-500">No attendance yet. End Work for Today closes only the current workday, not the whole project.</p>}</div><p className="mt-3 text-xs text-slate-500">Originally booked worker = Team Leader. Customer can increase team slots from Projects. Complete Project remains separate from daily work.</p></section>;
}
