import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, ChevronRight, FileText, Loader2, RefreshCw, X } from "lucide-react";
import { supabase } from "../../lib/supabase";
import { getMyReportDetails, getMyReports, subscribeToMyReports } from "../../services/caseReportService";
import type { ReportCase, ReportEvidence, ReportLog, ReportParticipantRole } from "../../types/report";

interface Props { role: ReportParticipantRole; layout: React.ComponentType<{children: React.ReactNode}>; }
const labels: Record<string,string>={submitted:"Submitted",under_review:"Under Review",needs_more_information:"Needs More Information",resolved:"Resolved",rejected:"Rejected",escalated:"Escalated",withdrawn:"Withdrawn",closed:"Closed"};
function statusClass(status:string){if(status==="resolved")return"bg-emerald-100 text-emerald-700";if(status==="rejected"||status==="closed")return"bg-red-100 text-red-700";if(status==="under_review"||status==="escalated")return"bg-blue-100 text-blue-700";return"bg-amber-100 text-amber-700";}

export default function MyReportsPage({role,layout:Layout}:Props){
 const [items,setItems]=useState<ReportCase[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [selected,setSelected]=useState<{report:ReportCase;evidence:Array<ReportEvidence&{signed_url:string|null}>;logs:ReportLog[]}|null>(null);const [detailsLoading,setDetailsLoading]=useState(false);
 const load=useCallback(async()=>{try{setError("");setItems(await getMyReports());}catch(e){setError(e instanceof Error?e.message:"Unable to load reports.");}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();let cleanup=()=>{};void supabase.auth.getUser().then(({data})=>{if(data.user)cleanup=subscribeToMyReports(data.user.id,()=>void load());});return()=>cleanup();},[load]);
 async function open(id:string){setDetailsLoading(true);try{setSelected(await getMyReportDetails(id));}finally{setDetailsLoading(false);}}
 return <Layout><div className="mx-auto max-w-6xl p-4 sm:p-8"><div className="mb-7 flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-wider text-blue-600">Case Management</p><h1 className="mt-1 text-3xl font-black text-slate-900 dark:text-white">My Reports & Complaints</h1><p className="mt-2 text-slate-500">Track cases you submitted as a {role}.</p></div><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 font-bold"><RefreshCw size={18}/>Refresh</button></div>
 {loading?<div className="flex min-h-64 items-center justify-center"><Loader2 className="animate-spin"/></div>:error?<div className="rounded-2xl bg-red-50 p-5 text-red-700">{error}</div>:items.length===0?<div className="rounded-3xl border border-slate-200 bg-white p-12 text-center shadow-sm"><AlertTriangle className="mx-auto text-slate-400" size={44}/><h2 className="mt-4 text-xl font-black">No cases submitted</h2><p className="mt-2 text-slate-500">Use Report User or File Complaint from a booking.</p></div>:<div className="grid gap-4">{items.map(item=><button key={item.id} onClick={()=>void open(item.id)} className="flex w-full items-center gap-4 rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md dark:border-slate-700 dark:bg-slate-900"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-red-50 text-red-600"><FileText/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-black capitalize">{item.case_type}: {item.subject}</p><span className={`rounded-full px-3 py-1 text-xs font-bold ${statusClass(item.status)}`}>{labels[item.status]??item.status}</span></div><p className="mt-1 text-sm text-slate-500">Booking #{item.booking_id} · {item.category} · {new Date(item.created_at).toLocaleString("en-PH")}</p></div><ChevronRight className="text-slate-400"/></button>)}</div>}
 {detailsLoading&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/40"><Loader2 className="animate-spin text-white" size={36}/></div>}
 {selected&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/65 p-3 backdrop-blur-sm"><div className="max-h-[94dvh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-white p-5 shadow-2xl dark:bg-slate-900 sm:p-7"><div className="flex items-start justify-between gap-4"><div><span className={`rounded-full px-3 py-1 text-xs font-bold ${statusClass(selected.report.status)}`}>{labels[selected.report.status]??selected.report.status}</span><h2 className="mt-3 text-2xl font-black">{selected.report.subject}</h2><p className="mt-1 text-sm text-slate-500">Booking #{selected.report.booking_id} · {selected.report.category}</p></div><button onClick={()=>setSelected(null)} className="rounded-xl p-2 hover:bg-slate-100"><X/></button></div><div className="mt-6 space-y-5"><section className="rounded-2xl bg-slate-50 p-5 dark:bg-slate-800"><h3 className="font-black">Description</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600 dark:text-slate-300">{selected.report.description}</p></section>{selected.report.resolution&&<section className="rounded-2xl bg-emerald-50 p-5 text-emerald-800"><h3 className="font-black">Resolution</h3><p className="mt-2">{selected.report.resolution}</p></section>}<section><h3 className="font-black">Evidence</h3>{selected.evidence.length===0?<p className="mt-2 text-sm text-slate-500">No evidence uploaded.</p>:<div className="mt-3 grid gap-3 sm:grid-cols-2">{selected.evidence.map(e=><a key={e.id} href={e.signed_url??undefined} target="_blank" rel="noreferrer" className="rounded-xl border border-slate-200 p-3 font-semibold hover:bg-slate-50">{e.file_name}</a>)}</div>}</section><section><h3 className="font-black">Timeline</h3><div className="mt-3 space-y-3">{selected.logs.map(log=><div key={log.id} className="border-l-4 border-blue-500 pl-4"><p className="font-bold">{log.note??log.action}</p><p className="text-xs text-slate-500">{new Date(log.created_at).toLocaleString("en-PH")}</p></div>)}</div></section></div></div></div>}
 </div></Layout>;
}
